---
- name: Setup ssh
  ansible.builtin.import_tasks: ssh.yml
  when: setup_ssh
  tags:
    - setup-secrets

- name: Setup vpn
  ansible.builtin.import_tasks: vpn.yml
  when: setup_vpn
  tags:
    - setup-secrets