---
- name: Create directory for ssh keys if it does not exist
  ansible.builtin.file:
    path: "{{ ssh_dir }}"
    state: directory
    mode: '0700'

- name: Rollout ssh keys
  ansible.builtin.copy:
    src: "files/{{ item.key }}"
    dest: "{{ ssh_dir }}/{{ item.key }}"
    mode: "{{ item.mode }}"
  loop: "{{ ssh_keys }}"