---
- name: Create directory for the vpn configuration {{ vpn_config_dir }}/{{ vpn_config_file }} (if it does not exist)
  ansible.builtin.file:
    path: "{{ vpn_dir}}/{{ item.dir }}"
    state: directory
    #owner: "{{ user }}"
    #group: "{{ group }}"
    mode: '0700'
  loop: "{{ vpn_configs }}"

- name: Rollout the vpn configuration {{ vpn_config_dir }}/{{ vpn_config_file }}
  ansible.builtin.template:
    src: "vpn-{{ item.dir }}/{{ item.file }}"
    dest: "{{ vpn_dir }}/{{ item.dir }}/{{ item.file }}"
    mode: '0600'
  loop: "{{ vpn_configs }}"