---
- name: Run the playbook tasks on the kali
  hosts: kali-default
  gather_facts: yes
  roles:
    - tools
    - desktop
    - services
    - basic-customization
    - desktop-customization
    - special-customization
    - secrets