---
- name: Remove libwacom2 for avoiding issues
  ansible.builtin.apt:
    name: libwacom2
    state: absent

- name: Install gnome desktop for kali
  ansible.builtin.apt:
    name: kali-desktop-gnome 
    state: present

- name: Deinstall xfce and related packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - kali-desktop-xfce 
    - xfce4* 
    - lightdm*
  when: install_desktop == "only-gnome"

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes

- name: Change the display manager to gdm3
  ansible.builtin.shell: |
    dpkg-reconfigure gdm3
  when: install_desktop == "only-gnome"

- name: Install dconf-editors
  ansible.builtin.apt:
    name: dconf-editor
    state: present