---
## 
# Setup repositories cache
##
apt_cached_updated: no


##
# Ansible
##
install_ansible: no


##
# Sublime Text & Sublime Merge
##
install_sublime_text: no
install_sublime_merge: no


##
# Obsidian
##
install_obsidian: no
obsidian_appimage_dest: "/opt/obsidian"
obsidian_version: 1.6.3


##
# Oracle instant client
##
install_oracle_instant_client: no
oracle_root: "/opt/oracle"
oracle_home: "{{ oracle_root }}/instantclient_21_1"
oracle_instant_client_version: "21.1.0.0.0"


##
# Burp Suite
##
install_burpsuite: no
burpsuite_edition: pro
burpsuite_installer_version: "2024.1.1.6"


##
# 1Password
##
install_1password: no
onepassword_arm_dest: "/opt/1Password"
onepassword_arm_version: "8.10.36"


##
# Chrome
##
install_chrome: no


##
# Terminator (terminator-config.j2)
##
setup_terminator: no
terminator_template: "terminator-config.j2"


##
# Git (gitconfig.j2)
##
setup_git: no
git_template: "gitconfig.j2"