---
- name: Remove previous installations
  ansible.builtin.file:
    path: "{{ onepassword_arm_dest }}"
    state: absent

- name: Download 1Password tarball
  ansible.builtin.get_url:
    url: "https://downloads.1password.com/linux/tar/stable/aarch64/1password-{{ onepassword_arm_version }}.arm64.tar.gz"
    dest: "/tmp/1password-{{ onepassword_arm_version }}.arm64.tar.gz"

- name: Extract 1Password tarball
  ansible.builtin.unarchive:
    src: "/tmp/1password-{{ onepassword_arm_version }}.arm64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: "Move extracted 1Password files to {{ onepassword_arm_dest }}"
  ansible.builtin.command: "sudo mv /tmp/1password-{{ onepassword_arm_version }}.arm64 {{ onepassword_arm_dest }}"

- name: Run after-install script
  ansible.builtin.command: "sudo {{ onepassword_arm_dest }}/after-install.sh"

- name: Remove 1Password tarball
  ansible.builtin.file:
    path: "/tmp/1password-{{ onepassword_arm_version }}.arm64.tar.gz"
    state: absent