---
- name: Set installer script filename
  ansible.builtin.set_fact:
    burpsuite_installer_script: "burpsuite_{{ burpsuite_edition }}_linux_v{{ burpsuite_installer_version | regex_replace('\\.', '_') }}.sh"

- name: Download Burp Suite installer
  ansible.builtin.get_url:
    url: "https://portswigger.net/burp/releases/download?product={{ burpsuite_edition }}&type=linux&version={{ burpsuite_installer_version }}"
    dest: "/tmp/{{ burpsuite_installer_script }}"
    #checksum: "sha256:{{ burpsuite_installer_sha256_checksum }}" # TODO
    #owner: "{{ user }}"
    #group: "{{ group }}"
    #mode: '0640'

- name: Create response.varfile for unattended install
  ansible.builtin.template:
    src: burpsuite_response.varfile.j2
    dest: /tmp/burpsuite_response.varfile
    #owner: "{{ user }}"
    #group: "{{ group }}"
    #mode: "0640"

- name: Install Burp Suite
  #become: yes
  #become_user: "{{ user }}"
  ansible.builtin.command:
    cmd: "/bin/sh /tmp/{{ burpsuite_installer_script }} -q -varfile /tmp/burpsuite_response.varfile -overwrite"
    #cmd: "/bin/sh /tmp/burpsuite_pro_linux_v2022_6_1.sh -q -varfile /tmp/burpsuite_response.varfile -overwrite"
    #chdir: /tmp
  #changed_when: true
