---
##
# Requirements
##
- set_fact:
    architecture: "{{ ansible_architecture }}"
    os_family: "{{ ansible_os_family }}"
  tags:
    - install-further-tools
    - install-obsidian
    - install-1password


##
# Install tools
## 
- name: Install apt packages
  become: yes
  ansible.builtin.import_tasks: apt.yml
  when: apt_packages is defined
  tags:
    - install-apt-tools

- name: Install Ansible
  become: yes
  ansible.builtin.import_tasks: ansible.yml
  when: install_ansible
  tags:
    - install-apt-tools
    - install-ansible

- name: Install tools from GitHub
  become: yes
  ansible.builtin.import_tasks: git.yml
  when: git_repos is defined
  tags:
    - install-git-tools

- name: Install Sublime Text and Sublime Merge
  become: yes
  ansible.builtin.import_tasks: sublime.yml
  when: install_sublime_text or install_sublime_merge
  tags:
    - install-apt-tools
    - install-sublime

- name: Install Obsidian (Debian package)
  become: yes
  ansible.builtin.import_tasks: deb-package.yml
  vars:
    url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ obsidian_version }}/obsidian_{{ obsidian_version }}_amd64.deb"
    package_name: "obsidian"
    deb_package: "obsidian_{{ obsidian_version }}_amd64.deb"
  when: install_obsidian and os_family == "Debian" and architecture == "x86_64"
  tags:
    - install-apt-tools
    - install-obsidian

- name: Install Obsidian (AppImage) for ARM architecture
  become: yes
  ansible.builtin.import_tasks: obsidian-appimage.yml
  vars:
    obsidian_appimage_file: "Obsidian-{{ obsidian_version }}-arm64.AppImage"
  when: install_obsidian and os_family == "Debian" and (architecture == "arm64" or architecture == "aarch64")
  tags:
    - install-further-tools
    - install-obsidian

- name: Install Oracle instant client
  become: yes
  ansible.builtin.import_tasks: oracle-instant-client.yml
  vars:
    oracle_instantclient_basic: "instantclient-basic-linux.x64-{{ oracle_instant_client_version }}.zip"
    oracle_instantclient_sqlplus: "instantclient-sqlplus-linux.x64-{{ oracle_instant_client_version }}.zip"
    oracle_instantclient_sdk: "instantclient-sdk-linux.x64-{{ oracle_instant_client_version }}.zip"
    oracle_download_url_prefix: "https://download.oracle.com/otn_software/linux/instantclient/{{ oracle_instant_client_version | replace('.','') }}"
  when: install_oracle_instant_client and os_family == "Debian" and architecture == "x86_64"
  tags:
    - install-further-tools

#- name: Install Burpsuite Professional
#  become: yes
#  ansible.builtin.import_tasks: burpsuite.yml
#  when: install_burpsuite
#  tags:
#    - install-further-tools
#    - install-burpsuite

- name: Install 1Password (Debian package)
  become: yes
  ansible.builtin.import_tasks: deb-package.yml
  vars:
    url: "https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb"
    package_name: "1password"
    deb_package: "1password-latest.deb"
  when: install_1password and os_family == "Debian" and architecture == "x86_64"
  tags:
    - install-further-tools
    - install-1password

- name: Install 1Password (ARM package)
  become: yes
  ansible.builtin.import_tasks: 1password-arm.yml
  when: install_1password and os_family == "Debian" and (architecture == "arm64" or architecture == "aarch64")
  tags:
    - install-further-tools
    - install-1password

- name: Build libsecret
  become: yes
  community.general.make:
    chdir: /usr/share/doc/git/contrib/credential/libsecret

- name: Install libu2f-udev (see https://www.petergirnus.com/blog/how-to-install-google-chrome-on-debian-linux)
  become: yes
  ansible.builtin.import_tasks: deb-package.yml
  vars:
    url: "http://archive.ubuntu.com/ubuntu/pool/main/libu/libu2f-host/libu2f-udev_1.1.4-1_all.deb"
    package_name: "libu2f-udev"
    deb_package: "libu2f-udev_1.1.4-1_all.deb"
  when: install_chrome and os_family == "Debian" and architecture == "x86_64"
  tags:
    - install-further-tools
    - install-chrome

- name: Install Chrome (Debian package)
  become: yes
  ansible.builtin.import_tasks: deb-package.yml
  vars:
    url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    package_name: "google-chrome"
    deb_package: "google-chrome-stable_current_amd64.deb"
  when: install_chrome and os_family == "Debian" and architecture == "x86_64"
  tags:
    - install-further-tools
    - install-chrome


##
# Setup links
##
- name: Create symbolic links
  become: yes
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    state: link
  loop: "{{ symlinks }}"
  when: symlinks is defined
  ignore_errors: true   # Errors clould occur, when a package was not installed or a repo was not checked out


###
# Setup installed tools
##
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Rollout configurations
  ansible.builtin.import_tasks: conf.yml
  vars:
    path: "{{ home_dir }}/.config/terminator"
    template: "{{ terminator_template }}"
    file_name: "config"
  when: "setup_terminator and ('terminator' in ansible_facts.packages)"

- name: Rollout configurations
  ansible.builtin.import_tasks: conf.yml
  vars:
    path: "{{ home_dir }}"
    template: "{{ git_template}}"
    file_name: ".gitconfig"
  when: "setup_git and ('git' in ansible_facts.packages)"