---
- name: Install GPG key for SubLime Text and Sublime Merge
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add specified repositories into sources list using specified filename
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
    filename: sublime

- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install Sublime Text
  apt: 
    name: sublime-text
  when: install_sublime_text

- name: Install Sublime Merge
  apt: 
    name: sublime-merge
  when: install_sublime_merge