---
- name: Install GPG key for SubLime Text and Sublime Merge
  ansible.builtin.apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add specified repositories into sources list using specified filename
  ansible.builtin.apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
    filename: sublime

- name: Update repositories cache
  ansible.builtin.apt:
    update_cache: yes

- name: Set repositories cache as updated
  set_fact:
    apt_cached_updated: yes

- name: Install Sublime Text
  ansible.builtin.apt: 
    name: sublime-text
  when: install_sublime_text

- name: Install Sublime Merge
  ansible.builtin.apt: 
    name: sublime-merge
  when: install_sublime_merge