---
##
# Configure User 
##
user: "kali"
group: "{{ user }}"
home_dir: "/home/{{ user }}"


##
# Setup SSH
##
setup_ssh: no
ssh_dir: "{{ home_dir }}/.ssh"


##
# Setup VPN
##
setup_vpn: no
vpn_dir: "{{ home_dir }}/.vpn"