--- 
- name: Install some tools via paket manager
  ansible.builtin.apt:
    name: pure-ftpd
    state: present

- name: Ensure group "ftpgroup" exists
  ansible.builtin.group:
    name: ftpgroup
    state: present

- name: Add the user ftpuser with a specific uid and a primary group of ftpgroup
  ansible.builtin.user:
    name: ftpuser
    shell: /etc
    home: /dev/null
    comment: ftpuser
    group: ftpgroup
    state: present 

- name: Create symbolic links
  ansible.builtin.file:
    src: /etc/pure-ftpd/conf/PureDB
    dest: /etc/pure-ftpd/auth/60pdb
    owner: root
    group: root
    state: link

- name: Create several directories
  ansible.builtin.file:
    path: /ftphome
    owner: ftpuser
    group: ftpgroup
    state: directory

- name: Restart the ftp service
  ansible.builtin.service:
    name: pure-ftpd
    state: started

- name: Run command if /path/to/database does not exist (without 'args')
  ansible.builtin.command: /usr/bin/pure-pw useradd offsec -u ftpuser -d /ftphome 

- name: Run command if /path/to/database does not exist (without 'args')
  ansible.builtin.command: /usr/bin/pure-pw mkdb

#groupadd ftpgroup
#useradd -g ftpgroup -d /dev/null -s /etc ftpuser 
#pure-pw useradd offsec -u ftpuser -d /ftphome 
#pure-pw mkdb
#cd /etc/pure-ftpd/auth/
#ln -s ../conf/PureDB 60pdb
#mkdir -p /ftphome
#chown -R ftpuser:ftpgroup /ftphome/
#systemctl restart pure-ftpd

# https://galaxy.ansible.com/robgmills/pure-ftpd