---
- name: Update repositories cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes
  when: not apt_cached_updated
  tags:
    - setup-desktop

- name: Set repositories cache as updated
  set_fact:
    apt_cached_updated: yes
  when: not apt_cached_updated
  tags:
    - setup-desktop

- name: Install kali wallpapers
  become: yes
  ansible.builtin.apt:
    name: kali-wallpapers-all
    state: present
  tags:
    - setup-desktop

- name: Setup GNOME desktop
  ansible.builtin.import_tasks: gnome-settings.yml
  when: setup_desktop == "only-gnome" or setup_desktop == "all"
  #when: "(setup_desktop == 'only-gnome' or setup_desktop == 'all') and ('git' in ansible_facts.packages)"
  #when: 'git' in ansible_facts.packages
  tags:
    - setup-desktop